### PR TITLE
feat: refactor buttons and links using custom properties

### LINKED ISSUE #188: Links: reevaluate visited states
**Describe the bug**

The visited state for links/calls to action is currently quite jarring.

### LINKED ISSUE #189: Review button and link styles and states for accessibility
**Describe the bug**
There are some buttons and link styles and states that are inconsistent and may pose accessibility issues. For example, some links visually appear as buttons, but are actually links. Some links and buttons have an outline when focused, while some change background colour.

These inconsistencies can create a barrier to understandability and predictability.

**Expected behavior**
Consistent visual language for focus, hover, current, visited, and active states.
Clear communication of intent of interactive elements that does not rely on colour alone.
Hover, focus, current, visited, and active states have sufficient colour contrast to adjacent colours.

Related to #188

### LINKED ISSUE #201: Implement new link styling for header links and CTAs
Implement changes to hover and focus styles for header links and CTAs to be more consistent with the overall focus and hover design for links. This addresses part of #189.

### LINKED ISSUE #202: Implement updated link styling for tag links
Implement styling changes for tag links to be more consistent with the overall design. Addresses part of #189 .

### LINKED ISSUE #204: Implement updated styling changes to button hover and focus states
Implement update styling changes to button hover and focus states for buttons (including those found in the navigation bar). Addresses part of #189 .

### LINKED ISSUE #208: Loooong tags
## Is your feature request related to a problem? Please describe.

Tags currently don't accommodate text that wraps beyond one line

Screen Shot 2020-01-28 at 3 24 55 PM

### LINKED ISSUE #219: Buttons on dark background
## Is your feature request related to a problem? Please describe.

Currently we don't have primary and secondary buttons designed specifically for dark backgrounds.

## Describe the solution you'd like

In the states table, preview here:
Screen Shot 2020-01-31 at 1 44 14 PM

## Describe alternatives you've considered

Also considered using blue 200 for the primary button, and while that looks good when dark mint 500 is the background, it doesn't look as good or provide as much contrast when it's paired with blue 500, which is the dark background that's used most in the screens right now.

### LINKED ISSUE #221: Borderless buttons - double up the focus borders
## Is your feature request related to a problem? Please describe.

Noticed that the current implementation of borderless buttons focus state for both light and dark only have 2 border.

## Describe the solution you'd like

Double 'em up please!
Screen Shot 2020-01-31 at 1 50 56 PM

### LINKED ISSUE #222: Spacing between borderless buttons
## Is your feature request related to a problem? Please describe.

Currently the borders are running into each other

## Describe the solution you'd like

Space 8px between each borderless button (counting the focus state), like so:
Screen Shot 2020-01-31 at 2 01 43 PM
(bottom is what it would look like spaced out, top is what it would look like without focus)
Please then also make the space between the CTA above and the borderless buttons below 20px.

### LINKED ISSUE #223: Spacing between link lists & accordions
## Is your feature request related to a problem? Please describe.

Currently the focus states are running into each other.

## Describe the solution you'd like

See below, left is current and right is proposed. The vertical height between the lines go from 44 to 54. Even though it inevitably still runs into other components due to just the nature of the line being on the outside, now it's a little less imposing (hopefully).
Screen Shot 2020-01-31 at 2 12 05 PM

### LINKED ISSUE #231: Pagination - Improve screen reader experience with additional descriptions
## Is your feature request related to a problem? Please describe.

Improve screen reader experience by adding detail to pager links.

## Describe the solution you'd like

Previous and Next links can have additional text information about the number of records Next will show. i.e. "Next 10 items." The number should be adjusted if Next will be the last page of items.

On the last pager link, add a screen reader accessible "(Last)" descriptor.
```html
<a class="page-numbers" href="61">61</a>
<span class="screen-reader-text">(Last)</span>
</a>
```

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

- [x] Link (Default, External, Relative)
- [x] Inverse Link (Default, External, Relative)
- [x] Breadcrumb Link
- [x] Tag
- [x] Button
- [x] Secondary Button
- [x] Borderless Button
- [x] Disc Button
- [x] Tag Button
- [x] Submit Button
- [x] Menu
- [x] Menu Button
- [x] Card
- [x] Accordion
- [x] Link List
- [x] Filter List
- [x] Pagination
- [x] Notification
- [x] Search Form
- [x] Disclosure Button
- [x] Saved Search
- [x] Info Card
- [x] Archive
- [x] Resource
- [x] Home

## Steps to test

Review:

- [Link](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--default.html)
- [Link (External)](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--external.html)
- [Link (Relative)](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--relative.html)
- [Inverse Link](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--default-inverse.html)
- [Inverse Link (External)](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--external-inverse.html)
- [Inverse Link (Relative)](https://deploy-preview-229--pinecone.netlify.com/components/preview/link--relative-inverse.html)
- [Breadcrumb Link](https://deploy-preview-229--pinecone.netlify.com/components/detail/link--breadcrumb.html)
- [Tag](https://deploy-preview-229--pinecone.netlify.com/components/preview/tag.html)
- [Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/button--default.html)
- [Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/detail/button--inverse.html)
- [Secondary Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/button--secondary.html)
- [Secondary Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/detail/button--secondary-inverse.html)
- [Borderless Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/button--borderless.html)
- [Borderless Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/detail/button--borderless-inverse.html)
- [Disc Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/button--disc.html)
- [Disc Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/detail/button--disc-inverse.html)
- [Tag Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/button--tag-button.html)
- [Submit Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/submit--default.html)
- [Submit Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/submit--default-inverse.html)
- [Menu](https://deploy-preview-229--pinecone.netlify.com/components/preview/menu--default.html)
- [Menu (Home)](https://deploy-preview-229--pinecone.netlify.com/components/preview/menu--home.html)
- [Menu Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/menu-button.html)
- [Menu Button (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/menu-button--inverse.html)
- [Card](https://deploy-preview-229--pinecone.netlify.com/components/preview/card--resource.html)
- [Accordion](https://deploy-preview-229--pinecone.netlify.com/components/preview/accordion--default.html)
- [Accordion (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/accordion--inverse.html)
- [Pagination](https://deploy-preview-229--pinecone.netlify.com/components/preview/pagination--default.html)
- [Pagination (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/pagination--inverse.html)
- [Link List](https://deploy-preview-229--pinecone.netlify.com/components/preview/link-list--default.html)
- [Link List (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/link-list--inverse.html)
- [Filter List](https://deploy-preview-229--pinecone.netlify.com/components/preview/filter-list.html)
- [Notification](https://deploy-preview-229--pinecone.netlify.com/components/preview/notification--default.html)
- [Search Form](https://deploy-preview-229--pinecone.netlify.com/components/preview/search--default.html)
- [Search Form (Inverse)](https://deploy-preview-229--pinecone.netlify.com/components/preview/search--inverse.html)
- [Search Form (Home)](https://deploy-preview-229--pinecone.netlify.com/components/preview/search--home.html)
- [Disclosure Button](https://deploy-preview-229--pinecone.netlify.com/components/preview/disclosure-button.html)
- [Saved Search](https://deploy-preview-229--pinecone.netlify.com/components/preview/saved-search.html)
- [Info Card](https://deploy-preview-229--pinecone.netlify.com/components/preview/info-card.html)
- [Archive](https://deploy-preview-229--pinecone.netlify.com/components/preview/archive.html)
- [Resource](https://deploy-preview-229--pinecone.netlify.com/components/preview/resource.html)
- [Home](https://deploy-preview-229--pinecone.netlify.com/components/preview/home.html)

## Additional information

Not applicable.

## Related issues

- Resolves #188.
- Resolves #189.
- Resolves #201.
- Resolves #202.
- Resolves #204.
- Resolves #208.
- Resolves #219.
- Resolves #221.
- Resolves #222.
- Resolves #223.
- Resolves #231.

### CODE REVIEW

**Comment by greatislander** [comment]
@cherylhjli @jhung @dayotte This is ready for review, with the exception of the navigation menu. I've linked all the components that need to be inspected in the PR description. I'll add an additional comment when I've completed the navigation menu.

**Comment by jhung** [comment]
@greatislander It seems that if a link is both active and is focused, the focus outline disappears.

Focus:
image

Focus + Active (current):
image

Focus + Active (proposed):
image

**Comment by greatislander** [comment]
@jhung This should now be addressed.

**Comment by cherylhjli** [comment]
- Links with right chevron and breadcrumb link: can we bring it closer to the text by 1/3 of the distance there is now?
- All links:
    - All browsers, active state - Is there a particular accessibility reason why there’s a box around the link? 
- Tags: 
    - In Chrome and Firefox, the active state for tags isn’t there - focus overriding active?
    - In Safari, the double outline has different thicknesses
    - In Chrome, can you move the text a a pixel or two down? It’s not as horizontally centred as the tags in safari and firefox
- Button:
    - In Chrome, the active state isn’t there - focus overriding active
- Button inverse:
    - Upon hover, the text changes to white - should be blue 500
    - In Chrome, there’s no active state - the text doesn’t change to blue 400
- Secondary button:
    - All browsers, hover state - the text changes to white - should be blue 500
    - In Chrome, active state - has a 2px border instead of the regular 1px thin one
- Secondary button inverse:
    - In Chrome, active state - the text disappears - should be white
    - In Chrome, active state - the border has a 2px border instead of regular 1px thin one
    - All browsers, focus state - the text disappears - should be white
- Borderless button
    - In Chrome, active state - the text should be blue 500 - in chrome it looks like dark mint, in firefox and safari it looks like blue 400
- Borderless button inverse:
    - In Chrome, the active state isn’t there - focus overriding active?
- Disc button:
    - In Chrome, the active state isn’t there - focus overriding active?
- Disc button inverse:
    - I notice that upon active state, the colour of the button is the same as a common background (blue 500), so let’s change the active state colour to blue 400?
- Tag button:
    - In Chrome, the active state isn’t there - focus overriding active?
- Submit button:
    - Same as button
- Submit button inverse:
    - Same as button inverse
- Menu
    - Bring the downward chevron closer to the label, half the distance it is now
    - Upon opening the language dropdown, “English” is not in alignment
    - Each drop down menu is a different width depending on the size of the content - can we make it all consistently 250px wide?
- Menu home:
    - Same comments as Menu component 
- Menu button
    - All browsers - Currently the only way to close the dropdown is to click on the button again. Can we make it so that the dropdown also closes if one clicks outside of the drop down area, anywhere else on the page? I think this is a pretty standard pattern in other places on the web, it took me awhile to figure out I had to click the button again to close it
    - The dropdown doesn’t have a hover state - can we make the text blue 500, and hover state dark mint 500 to be consistent with the links
- Menu button inverse
    - Safari, focus state - for the double border, the inner one is thicker than the outer one - can we make it so that they’re both thick (2px)?
- Card:
    - All browsers: The heart icon and the “favourite” label isn’t horizontally centred - this is especially obvious in Safari - can this be a bit more lined up?
    - All browsers: Is there any way to make the padding between the badges the favourite label a little less?
    - All browsers: The typeface of the title of the card should be noto sans, instead of noto sans display
- Accordion:
    - Chrome, active state: Not consistent with the active states in firefox and safari, which is just a change in text colour to blue 400
    - Can the top line be a bit thicker by a pixel?
- Accordion inverse:
    - Same as Accordion component, except active state text should be blue 200
- Pagination:
    - All browsers, hover state: underline should be blue 300 to be consistent with the other links
- Pagination inverse:
    - All browsers, hover state: underline should be blue 300 to be consistent with the other links, text also turns dark instead of white, causing it to blend into the background
    - Chrome and firefox, active state: don’t need circular border around it, just need the text and underline to be blue 200 Safari, active state: text and underline to be blue 200
- List links:
    - Chrome and firefox, active state - I noticed that in the safari active state that the line stays at 2px instead of 1px - can chrome and firefox match? I find it much more of a clear visual treatment for this state to indicate something is happening
- List links inverse:
    - Same as List links component above
- Filter list:
    - All browsers - can we move the checkbox and the associated label just a pixel or two down, so it’s centred vertically between the two lines that are sandwiching it?
- Search form:
    - All browsers, focus state: For the search field itself, there should be a double outline upon focus
    - All browsers, hover state: For the search field itself, thicken the stroke to 2px
- Search form inverse:
    - All browsers, hover state: No hover state visible, please turn background of the button to blue 150
    - Same comment as Search Form component above about the focus state and hover state
    - Safari, focus state: For the search button, something funky is happening when focused: [screenshot here]
- Search form home page:
    - Same comments as Search Form inverse above
- Disclosure button:
    - Can you move the downward chevron a pixel or two closer to the label?
- Info card
    - All browsers - Add a bit more padding to the top of the card, so that it’s the same amount of space as the padding at the bottom of the card
    - All browsers - the close button - could the distance to the right be as same as the distance to the top? 
- Resource page
    - This is my bad, but I forgot to make an issue for the updated format to this page, here it is:
    - I also noticed the cards at the bottom of this page are outdated
    - Add icon for report broken link
- Home page
    - All browsers - Reduce the padding between “my feed” and the top and bottom edges - by around 1/3 of what it is now
    - All browsers - Reduce padding between “most viewed” and the cards below to 30px

**Comment by jhung** [comment]
If link is visited, active, and focused, the link text is invisible on a white background.

image

This is caused by the visited link style overriding the color:

`.link--breadcrumb:visited:focus, .link--inverse:visited:focus, a:visited:focus:not([class]), .link:visited:focus {
    color: var(--focus-color);
}`

--focus-color is white.

**Comment by jhung** [comment]
@cherylhjli said:
>       * All browsers, active state - Is there a particular accessibility reason why there’s a box around the link?

I think active and focus state should be visually distinct so there's no confusion what has focus and what is active.

To me something like this would work:

:active
image

:focus
image

:active:focus*
image
*change text color to match border colour, and remove underline from text.

**Comment by greatislander** [comment]
> If link is visited, active, and focused, the link text is invisible on a white background.

Fixed in cce11fd.

**Comment by greatislander** [comment]
>     * Links (not inverse):
>       * Firefox, active + focused: the text inside disappears

Fixed in cce11fd.

**Comment by greatislander** [comment]
* Tags:
    * In Chrome and Firefox, the active state for tags don’t include the 1px border
    * In Safari, the double outline has different thicknesses

Fixed in 55ebb27.

**Comment by greatislander** [comment]
> Secondary button:
> All browsers, hover state - the text changes to white - should be blue 500

Fixed in 9b5b018.

**Comment by greatislander** [comment]
* Borderless button
  * In Chrome, active state - the text should be blue 500 - in chrome it looks like dark mint, in firefox and safari it looks like blue 400

Fixed in 02d1b7c.

**Comment by greatislander** [comment]
* Disc button inverse:
  * I notice that upon active state, the colour of the button is the same as a common background (blue 500), so let’s change the active state colour to blue 400?

Fixed in a3ef748.

**Comment by greatislander** [comment]
@cherylhjli:

- Links with right chevron and breadcrumb link: can we bring it closer to the text by 1/3 of the distance there is now?
- Links (not inverse):
    - Firefox, active + focused: the text inside disappears
    - Fixed in cce11fd.
- Tags: 
    - In Chrome and Firefox, the active state for tags don’t include the 1px border
    - In Safari, the double outline has different thicknesses
	- Fixed in 55ebb27.
- Secondary button:
    - All browsers, hover state - the text changes to white - should be blue 500
    - Fixed in 9b5b018.
- Borderless button
    - In Chrome, active state - the text should be blue 500 - in chrome it looks like dark mint, in firefox and safari it looks like blue 400
- Disc button inverse:
    - I notice that upon active state, the colour of the button is the same as a common background (blue 500), so let’s change the active state colour to blue 400?
- Submit button:
    - Same as button
- Submit button inverse:
    - Same as button inverse
- Menu
    - Bring the downward chevron closer to the label, half the distance it is now
    - Upon opening the language dropdown, “English” is not in alignment
    - Each drop down menu is a different width depending on the size of the content - can we make it all consistently 250px wide?
- Menu home:
    - Same comments as Menu component 
- Menu button
    - All browsers - Currently the only way to close the dropdown is to click on the button again. Can we make it so that the dropdown also closes if one clicks outside of the drop down area, anywhere else on the page? I think this is a pretty standard pattern in other places on the web, it took me awhile to figure out I had to click the button again to close it
    - The dropdown doesn’t have a hover state - can we make the text blue 500, and hover state dark mint 500 to be consistent with the links
- Menu button inverse
    - Safari, focus state - for the double border, the inner one is thicker than the outer one - can we make it so that they’re both thick (2px)?
- Card:
    - All browsers: The heart icon and the “favourite” label isn’t horizontally centred - this is especially obvious in Safari - can this be a bit more lined up?
    - All browsers: Is there any way to make the padding between the badges the favourite label a little less?
    - All browsers: The typeface of the title of the card should be noto sans, instead of noto sans display
- Accordion:
    - Chrome, active state: Not consistent with the active states in firefox and safari, which is just a change in text colour to blue 400
    - Can the top line be a bit thicker by a pixel?
- Accordion inverse:
    - Same as Accordion component, except active state text should be blue 200
- Pagination:
    - All browsers, hover state: underline should be blue 300 to be consistent with the other links
- Pagination inverse:
    - All browsers, hover state: underline should be blue 300 to be consistent with the other links, text also turns dark instead of white, causing it to blend into the background
    - Chrome and firefox, active state: don’t need circular border around it, just need the text and underline to be blue 200 Safari, active state: text and underline to be blue 200
- List links:
    - Chrome and firefox, active state - I noticed that in the safari active state that the line stays at 2px instead of 1px - can chrome and firefox match? I find it much more of a clear visual treatment for this state to indicate something is happening
- List links inverse:
    - Same as List links component above
- Filter list:
    - All browsers - can we move the checkbox and the associated label just a pixel or two down, so it’s centred vertically between the two lines that are sandwiching it?
- Search form:
    - All browsers, focus state: For the search field itself, there should be a double outline upon focus
    - All browsers, hover state: For the search field itself, thicken the stroke to 2px
- Search form inverse:
    - All browsers, hover state: No hover state visible, please turn background of the button to blue 150
    - Same comment as Search Form component above about the focus state and hover state
    - Safari, focus state: For the search button, something funky is happening when focused: 
Screen Shot 2020-02-07 at 12 30 43 PM

- Search form home page:
    - Same comments as Search Form inverse above
- Disclosure button:
    - Can you move the downward chevron a pixel or two closer to the label?
- Info card
    - All browsers - Add a bit more padding to the top of the card, so that it’s the same amount of space as the padding at the bottom of the card
    - All browsers - the close button - could the distance to the right be as same as the distance to the top? 
- Resource page
    - This is my bad, but I forgot to make an issue for the updated format to this page, here it is:
Screen Shot 2020-02-07 at 12 55 33 PM

    - I also noticed the cards at the bottom of this page are outdated
    - Add icon for report broken link

- Home page
    - All browsers - Reduce the padding between “my feed” and the top and bottom edges - by around 1/3 of what it is now
    - All browsers - Reduce padding between “most viewed” and the cards below to 30px

**Comment by greatislander** [comment]
> @jhung said:
> I think active and focus state should be visually distinct so there's no confusion what has focus and what is active.
> 
> To me something like this would work:
> 
> :active
> image
> 
> :focus
> image
> 
> :active:focus*
> image
> *change text color to match border colour, and remove underline from text.

I'm wondering if we need a separate focus + active style? Was just reading up and came across this: https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/

She suggests that you should add styles in order of interaction, so: first hover, then focus, then active. Which would mean that active would always outweight the others (since — as far as I know — you can't have one element focused while a different element is active). Thoughts @jhung?

**Comment by jhung** [comment]
> I'm wondering if we need a separate focus + active style? Was just reading up and came across this: https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/
> 
> She suggests that you should add styles in order of interaction, so: first hover, then focus, then active. Which would mean that active would always outweight the others (since — as far as I know — you can't have one element focused while a different element is active). Thoughts @jhung?

@greatislander I thought about this and while (currently) it's impossible to have active without a focus state, the spec implies that active and focus should be treated differently. Also there may be situations we did not think of (or anticipate in the future) where active elements may not receive focus. Also, it seems cleaner to not overload `:active` with focus styles and use `:active:focus` for that.

I think the following tweak to the active and focus styles may make more sense. tl;dr Active state causes a background change, focus is a border, active with focus is a background change with a border. What do you think? @cherylhjli thoughts?

**Normal**

default:
image

:active
image

:focus
image

:active:focus
image

**Inverse**

default:
image

:active
image

:focus
image

:active:focus
image

**Comment by cherylhjli** [comment]
Everything looks great, a few small things:

Menu
* Bring the downward chevron closer to the label, half the distance it is now - **can this still be closer? By a third of the distance?**
* Can we make the height of the sub-menu items only 50px high? Right now its huge

Menu button
- Focus state of options in the dropdown - can we double border it? Right now it doesn’t have a border

Pagination (both regular and inverse)
- Active state in firefox and chrome: There’s still a circle around it

List links:
* Chrome and firefox, active state - I noticed that in the safari active state that the line stays at 2px instead of 1px - can chrome and firefox match? I find it much more of a clear visual treatment for this state to indicate something is happening **- it doesn’t look like the thickness is the same between hover and active in chrome and firefox, can it both be the thickness of the current hover state?**

**Comment by greatislander** [comment]
@cherylhjli Fixed these last issues.

**Pull request merged**
