### PR TITLE
feat: tabs (resolves #337)

### LINKED ISSUE #337: Molecule: tabbed view
## Is your feature request related to a problem? Please describe.

We need a tabbed content view.

## Describe the solution you'd like

Functionality should match [ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices/#tabpanel). Some design elements to be determined.

## Describe alternatives you've considered

Not applicable.

## Additional context

This looks cool: https://github.com/zachleat/seven-minute-tabs

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds tabs.

## Steps to test

Review component: https://deploy-preview-350--pinecone.netlify.app/components/preview/tabs

## Additional information

Based on https://github.com/zachleat/seven-minute-tabs and, by extension, https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html.

## Related issues

Resolves #337.

### CODE REVIEW

**Comment by cherylhjli** [comment]
Looks great! For the desktop version can a grey line be added on the bottom of the component? like this:
Screen Shot 2020-05-20 at 2 03 48 PM

**Comment by greatislander** [comment]
@cherylhjli Ready for review.

**Comment by cherylhjli** [comment]
Default looks great! I realized I didn't supply inverse designs, here they are:
https://xd.adobe.com/view/b3e417e8-8969-4cef-4af8-41e1b53d3cae-c5d5/screen/5fb061de-83c1-4031-a8da-3b07c8ade753/Web-1280-2

**Comment by greatislander** [comment]
@cherylhjli Inverse styles are ready for review.

**Comment by cherylhjli** [comment]
any chance the tabs on desktop could span the entire length of the page?

**Comment by greatislander** [comment]
@cherylhjli done.

**Pull request merged**
