### PR TITLE
Molecule: card

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds card components:

- [x] Blog
- [x] Co-op
- [x] Community Story
- [x] Event
- [x] News
- [x] Person
- [x] Project
- [x] Publication
- [x] Resource

## Steps to test

Review components:

- https://deploy-preview-50--pinecone.netlify.com/components/preview/card.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--resource.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--blog.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--event.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--platform-co-op.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--blog-with-image.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--person.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--story.html
- https://deploy-preview-50--pinecone.netlify.com/components/preview/card--project.html

## Additional information

- https://inclusive-components.design/cards/

## Related issues
Not applicable.

### CODE REVIEW

**Comment by greatislander** [comment]
Ping: @dayotte 🙂

**Comment by cherylhjli** [comment]
Looking great! A few tiny nit-picky things :)
- Resource card: The icon next to the resource type is missing? & the topics look a little off, compared to the mockup we landed on:
Screen Shot 2019-11-25 at 12 34 04 PM

- Event card: Can we add a few more pixels between the calendar/location icon and their associated info?
- All cards: Can we reduce the width of the content type tag by a few pixels, so that the space between the top-word-bottom matches the left-word-right?

**Comment by greatislander** [comment]
@cherylhjli Fixed, ready for final review.

**Comment by cherylhjli** [comment]
Resource card, event card: Is it possible to move the two small lines of text below the title closer together to each other, the distance of the two lines on the project card or people card? To create visual associations of certain content based on importance.

Event card: The calendar icon disappeared?

**Comment by greatislander** [comment]
@cherylhjli Fixed.

**Pull request merged**
