### PR TITLE
Fix buttons, tag links, and tag badges (resolves #86)

### LINKED ISSUE #86: Hover and focus state for link with icon
**Is your feature request related to a problem? Please describe.**
Adding a hover and focus state for link with icon (ex. "filter")

**Describe the solution you'd like**
What do you think about this, Ned?
Screen Shot 2019-12-09 at 3 49 51 PM

**Describe alternatives you've considered**
I know you initially described it as a "button", but upon looking at it again, I feel it's more akin to a link since it doesn't explicitly look like a button in the sense that there's a coloured box around it.

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

- Standardizes tag link and badge styles to match tag buttons;
- Adds new button style.

## Steps to test

Review components:

- https://deploy-preview-92--pinecone.netlify.com/components/detail/tag.html
- https://deploy-preview-92--pinecone.netlify.com/components/detail/badge.html
- https://deploy-preview-92--pinecone.netlify.com/components/detail/button.html
- https://deploy-preview-92--pinecone.netlify.com/components/detail/tag-button.html

## Additional information

Not applicable.

## Related issues

- Resolves #86.

### CODE REVIEW

**Comment by cherylhjli** [comment]
Badges: Font colour should be darkened to #203131 to pass AAA
Tag button: Could we decrease the width left and right of the 'x'? Maybe by around a third of what it is right now? The 'x' also looks a bit thin in stroke - this is using the newest icons, I'm assuming?

**Comment by cherylhjli** [comment]
In firefox, the tag upon click has the focus state instead of the active state

**Comment by greatislander** [comment]
> In firefox, the tag upon click has the focus state instead of the active state

This is the way Firefox behaves — clicking a link applies both the focus and active states.

**Comment by greatislander** [comment]
@cherylhjli I was able to add a workaround— see other links too

**Pull request merged**
