### PR TITLE
Improve icon system

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Improves icon system:

- Adds hidden `_svg` utility component.
- Adds full set of new icons.
- Updates existing components to use new icons.

## Steps to test

Review all components with icons: https://deploy-preview-83--pinecone.netlify.com/

## Additional information

Not applicable.

## Related issues

- Follow-up to #29 and #41.

### CODE REVIEW

**Comment by cherylhjli** [comment]
I realized that the warning icon was looking a bit big, and then realized I had messed up the size of the artboard in illustrator (it was 18x18, supposed to be 20x20) - I changed it in illustrator, hopefully that will help with making it the same size as the error icon.

Also, I think we're missing the language and discover icon?

Other than that this is looking GREAT.

**Comment by greatislander** [comment]
@cherylhjli I fixed the warning icon. I was a bit puzzled about the sizing for those last two—meant to ask you. They both have a 42px &times; 42px artboard; the language icon also has a 26px &times; 26.15px artboard. For the smaller variant, should it be scaled down to 24px &times 24px like the topic, goal, sector, and format icons?

**Comment by cherylhjli** [comment]
Good point - I took a look at the icons and resized the bigger icons to fit 40x40.
For the language icon unfortunately can't go any smaller - I tried scaling it to 24x24 and the lines in the globe get all murky. Is it too weird to have a 28x28? Would it be better to up it all the way to 32x32?

**Comment by greatislander** [comment]
If it works properly in context that's not a problem, I'd just double-check against the mobile language menu and see what size it is there

**Comment by greatislander** [comment]
Ready for another review @cherylhjli.

**Pull request merged**
