### PR TITLE
Adds mobile filter overlay styles, improve typography and spacing

### LINKED ISSUE #88: Implement filter overlay styling for mobile devices
**Is your feature request related to a problem? Please describe.**
As per design, with some modifications: https://xd.adobe.com/view/20bf01bb-13f4-4682-54ba-046ad4288da1-568e/

**Describe the solution you'd like**
TK.

**Describe alternatives you've considered**
TK.

**Additional context**
TK.

### LINKED ISSUE #110: Button style for dark backgrounds
The default button (https://pinecone.platform.coop/components/preview/button.html) needs a variant for dark backgrounds.

### LINKED ISSUE #120: Typography spacing
**Is your feature request related to a problem? Please describe.**
Currently typography spacing needs work - creates awkward gaps on certain pages. Also lacking in tablet and mobile specs.

**Describe the solution you'd like**
Updated the typography spacing in the PCC_ComponentLibrary file, as well as here:
Desktop: https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/b80cf480-e8cd-4926-bdc1-48a7a035b1e2/01-Style-Guide-Icons-Dividers-1/
Tablet: https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/798dc8a7-25f3-46a7-8483-ae37f8c2f704/01-Style-Guide-Icons-Dividers-2
Mobile: https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/67d9aef4-c04c-469f-a44d-adb10626eb04/01-Style-Guide-Icons-Dividers-3

### LINKED ISSUE #121: Updated typestack
**Is your feature request related to a problem? Please describe.**
While working on typography spacing, found a few updates that were needed for the typestack in order for the system to work together cohesively.

**Describe the solution you'd like**
Tablet H2 changed to 28/40
https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/b76b2824-d007-4c76-a901-91da046fd56c/01-Style-Guide-Typography-Tablet

Mobile H4 changed to 18/26 (still bold)
Mobile pull quotes changed to 18/26 (semibold italic)
https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/1204e4ef-deae-46a2-99f1-40d7b31986e7/01-Style-Guide-Typography-Mobile

### LINKED ISSUE #125: Updated tag style
**Is your feature request related to a problem? Please describe.**
Noticed that the tag style in Pinecone is a bit out of date after we adjusted the visual design on the resource detail page.

**Describe the solution you'd like**
Screen Shot 2020-01-06 at 11 56 04 AM
Fill: #E3EAE8
Text: #18514F

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds proper styles for mobile filter overlay, cleans up some typography, standardizes vertical spacing.

## Steps to test

Review component: https://deploy-preview-111--pinecone.netlify.com/components/preview/archive.html

## Additional information

Not applicable.

## Related issues

- Resolves #88.
- Resolves #110.
- Resolves #120.
- Resolves #121.
- Partially addresses #122 (browse page spacing only).
- Resolves #125.

### CODE REVIEW

**Comment by cherylhjli** [comment]
Mobile filter PR
- Can “close” be closer to the top right corner? By half the distance it is now?
- “Deselect all” - can the text be left aligned with the “locations…” above and checkbox below? I guess that might call for a pressed/active state that then won’t run into the edges of the screen
Screen Shot 2020-01-08 at 2 12 20 PM

- The dividers in between the checkboxes, between the checkbox and ‘deselect all”, should be #203131.
- When drilling down one more level into the checkboxes that have layers underneath it, the bg colour changes to #203131.
Screen Shot 2020-01-08 at 2 16 00 PM

- Can the button to apply filter be sticky on a grey 200 background, like so?
Screen Shot 2020-01-08 at 2 16 41 PM

Typestack:
- On mobile, let’s make the pull quotes 16px… 18px is making a really awful edge
Screen Shot 2020-01-08 at 2 27 20 PM

- Can the attribution of the pull quote be regular body text but italic?

Typography spacing:
- Padding between the pull quotes and body text on either side can decrease to be the same as the padding between paragraphs

Padding on browse all page:
- Spacing between top of filter to the edge of the off-white a bit too tall - try decreasing by 1/4 of what it currently is
- Decrease spacing between end of card and pagination component by 1/3, add more spacing to end of pagination and beginning of footer (unless this hasn’t been coded yet)

**Comment by greatislander** [comment]
> * “Deselect all” - can the text be left aligned with the “locations…” above and checkbox below? I guess that might call for a pressed/active state that then won’t run into the edges of the screen

I think this is an issue with the "borderless" button style. It necessitates padding which could look like a mistake until the hover/focus states are revealed. I'm open to suggestions, but I worry that shifting it left will make the hover/focus states look odd.

**Comment by greatislander** [comment]
> * On mobile, let’s make the pull quotes 16px… 18px is making a really awful edge

I could do that or I could remove the right margin on mobile. Looks much better even at 18px.

Improved blockquotes

**Comment by greatislander** [comment]
> * Spacing between top of filter to the edge of the off-white a bit too tall - try decreasing by 1/4 of what it currently is

I'm not sure what you mean by this @cherylhjli — can you send a screenshot?

**Comment by greatislander** [comment]
@cherylhjli Made some updates, see comments. Ready for re-review.

**Pull request merged**
