### PR TITLE
feat: add search bar to menu (resolves #178)

### LINKED ISSUE #178: Menu: opening a dropdown via click event does not close already open dropdowns
**Describe the bug**

If a dropdown is open on desktop, opening another dropdown with the mouse (by clicking its button) should close the other dropdown. It does not currently do so.

**To Reproduce**

1. Visit the menus component.
2. Open a dropdown.
3. Open another dropdown with the mouse.

**Expected behavior**

The first dropdown should close as the second opens. Instead, it remains open.

**Screenshots**

Multiple dropdowns expanded.

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: Firefox
 - Version: 72.0.1

**Additional context**

Not applicable.

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds a search bar to the menu. On mobile devices, the input is hidden by default but can be revealed by pressing a toggle button. The search input can be hidden by pressing escape, tabbing into the menu, or pressing the toggle button again.

Also resolves #178; an open menu dropdown should be collapsed if another is expanded via click event.

## Steps to test

Review menu components (default and home) at all screen sizes.

## Additional information

Not applicable.

## Related issues

- Blocks https://github.com/platform-coop-toolkit/coop-library/issues/116.
- Resolves #178.

### CODE REVIEW

**Comment by cherylhjli** [comment]
It looks great! Is it possible for the search button to be square? It looks a little rectangular right now.
Also I don't think the home page nav needs a search bar as there's a giant prominent one in the center of the page.

**Comment by greatislander** [comment]
@cherylhjli Fixed.

**Comment by cherylhjli** [comment]
Aspect ratio looks great, it looks like the search bar is still there on the home page though:

Screen Shot 2020-01-23 at 2 38 51 PM

**Comment by greatislander** [comment]
https://deploy-preview-182--pinecone.netlify.com/components/preview/menu--home.html ?

**Comment by greatislander** [comment]
Fixed now — deploying @cherylhjli

**Comment by jhung** [comment]
The Search submit button doesn't have a text label, but the dev branch of the Search molecule has a text label. Is this because some changes have not been merged?

The span inside the label is also empty, which can be removed since the form has `role=search` already.

**Comment by greatislander** [comment]
@jhung to clarify, should the label wrapper around the search input be removed altogether? I've fixed the button text in 9d6f76c (I wasn't rendering the search component properly).

**Pull request merged**
