### PR TITLE
Atom: badges, tags, tag buttons

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds badges, tags, and tag buttons.

## Steps to test

Review components:

- https://deploy-preview-49--pinecone.netlify.com/components/detail/badges.html
- https://deploy-preview-49--pinecone.netlify.com/components/detail/tags.html
- https://deploy-preview-49--pinecone.netlify.com/components/detail/tag-buttons.html

## Additional information

Not applicable.

## Related issues

Not applicable.

### CODE REVIEW

**Comment by greatislander** [comment]
Ping: @dayotte 🙂

**Comment by cherylhjli** [comment]
These are on point!

Super small thing - for the tags, could we bring the width in by a few pixels on the left/right so that it matches the width on the top/bottom? (same comment as the tags on the cards)

**Comment by greatislander** [comment]
@cherylhjli Fixed, ready for final review.

**Comment by cherylhjli** [comment]
They look good! Only thing:
It looks like the text on the tag buttons are sitting a little low?

**Comment by greatislander** [comment]
@cherylhjli Fixed.

**Pull request merged**
