### PR TITLE
feat: add disclosure button (resolves #150)

### LINKED ISSUE #150: Atom: disclosure button
**Is your feature request related to a problem? Please describe.**

Add disclosure button molecule.

**Describe the solution you'd like**

Implement disclosure button as found in saved search (XD, Resource Core Screens).

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Blocks #151.

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Adds disclosure button component.

## Steps to test

Review component:

- https://deploy-preview-154--pinecone.netlify.com/components/preview/disclosure-button.html

## Additional information

Not applicable.

## Related issues

- Resolves #150.

### CODE REVIEW

**Comment by jhung** [comment]
I was reviewing this component and I realized that depending on the context, it is semantically better to use the native `<summary><details>` pattern instead of a button with Javascript. Summary-details would make sense for some of the text content such as notifications and paragraph text.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Summary-Details should not be used in cases like the sidebar navigation - semantically it won't make sense as a parent item is not a summary of the sub items.

All that said, this disclosure component is still useful, but summary-detailis should be used instead where it is appropriate.

**Comment by greatislander** [comment]
@jhung I've merged as-is. It looks like there's some weird workarounds needed to style summary/details the way the designs specify, and it would need to be polyfilled for IE/non-Chromium Edge. Can you create a follow-up issue for this?

**Comment by cherylhjli** [comment]
Is there a way to bump the up chevron arrow down a little bit, or would that affect the down chevron as well?

**Comment by greatislander** [comment]
It would affect the down chevron as well and if the vertical positioning changed between states the rotation would look weird (it would shift up/down while rotating).

**Comment by cherylhjli** [comment]
ok, don't worry about it then! it works as it is

**Pull request merged**
