### PR TITLE
fix: call-to-action, accordion, tags, and filter list state styling

### LINKED ISSUE #316: Tag links focus style does not match focus style in wireframes
## Is your feature request related to a problem? Please describe.

Tag links do not have the proper focus styling: https://pinecone.netlify.app/components/detail/tag.html

Currently:
image

Expected (from wireframe):
image

### LINKED ISSUE #359: Call to action text not legible due to color
## Describe the bug

The color for the Call to Action text appears white-on-white. The color should be the same as parent background color.

image

### LINKED ISSUE #362: Tag button missing active state
The tag button is missing an active state. Should follow the design spec.

From design:
image

### LINKED ISSUE #366: Accordion and Link List styles do not match designs
## Is your feature request related to a problem? Please describe.
The current accordion styles should be updated to match the designs.

Update: Link List styles are [now fixed](https://github.com/platform-coop-toolkit/pinecone/pull/379).

image

image

### PR DESCRIPTION
**Pull request by jhung**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)

* [x] This isn't a duplicate of an existing pull request

## Description
This PR addresses a number of styling issues:

* [x] Call to action text not readable when inverted (Fixes #359 )
* [x] Accordion does not use the proper focus and active styles (Fixes #366 )
* [x] Tag missing active state (Fixes #362 )
* [x] Tag focus border is partly too thin (Fixes #316)

## Steps to test

1. Go to the deployed instance for this PR: https://deploy-preview-380--pinecone.netlify.app/
2. Examine:
   * Atom > Tag
   * Molecule > Accordion
   * Molecule > Filter List
   * Layout > Search Results (check Filter list)
   * Layout > Archive (check Filter list)
   * Layout > Resource (check Tags)

**Expected behavior:**

The focus, hover, and active states should look like the design spec in major current browsers.

## Related issues
Fixes #359 
Fixes #366 
Fixes #362 
Fixes #316

### CODE REVIEW

**Comment by jhung** [comment]
@greatislander the issue you observed only happens if you use the debugger. If using keyboard or mouse to activate the various states, the top-border of the item below properly hides.

Putting PR back into draft - I found an issue with the mobile view on Filter List that needs to be fixed.

**Comment by greatislander** [comment]
@jhung It happens for me during regular use too.

**Comment by greatislander** [comment]
@jhung Will you have any capacity to wrap this up on Monday? Would like to get these styles into a release.

**Comment by cherylhjli** [comment]
hey @jhung, a few things come up for me - 

- In the filter list for the archive layout and search result layout, the filter list checkboxes disappear or are a very low contrast colour  in all browsers:

Screen Shot 2020-06-22 at 11 02 41 AM
Screen Shot 2020-06-22 at 11 02 51 AM
Screen Shot 2020-06-22 at 11 01 51 AM
Screen Shot 2020-06-22 at 11 02 36 AM

Also noticed that in safari, in the resource page, the CTA text is black instead of white:
Screen Shot 2020-06-22 at 11 05 04 AM

**Comment by greatislander** [comment]
@jhung The filter list form needs a `.form` class (that should resolve the first of @cherylhjli's comments). As for the CTA I'm not sure but that needs to be resolved as this PR is supposed to fix CTAs.

**Comment by jhung** [comment]
@cherylhjli - fixed the CTA issue and the checkbox borders not appearing correctly.

There's another issue with the Archive filter list - all the child filter items are all showing up as "checkbox". This will be looked at in a different PR.

**Comment by cherylhjli** [comment]
@jhung the CTA looks great, the checkboxes are still disappearing for me?

**Comment by jhung** [comment]
> 
> 
> I missed that issue @cherylhjli identified; I think it should be resolved in this PR. Sorry @jhung. I expect it is related to the "Checkbox" issue.

The IDs were being all set to 'checkbox', so it appeared that the checkboxes were not working. The logic for setting the `for` and `id` in the checkbox template doesn't seem to be working if a `value` was not set in the template configuration file.

For now I've worked around the issue by giving values for all children checkboxes. Ideally the ID generation for the checkbox should be less fragile (perhaps using faker or nunjucks random to generate unique IDs where needed).

**Comment by greatislander** [comment]
@jhung https://github.com/jhung/pinecone/pull/1

**Pull request merged**
